title: VGalaxies
description: Personal site — visual reading notes
url: "https://vgalaxies.github.io"
baseurl: ""

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

include:
  - _pages
  - files

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
